[package]
name = "hello_world_guest"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "3.0.3"}
hello_world_witness = { path = "../../../hello_world_witness", default-features = true}
